version: 2

defaults: &defaults
  working_directory: ~/lynx
  docker:
    - image: circleci/node:10.8-browsers

jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v0.1-npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
            - v0.1-npm-cache-{{ .Branch }}
            - v0.1-npm-cache-master-{{ checksum "package.json" }}
            - v0.1-npm-cache-master

      - restore_cache:
          keys:
            - v0.2-bower-cache-{{ .Branch }}-{{ checksum "bower.json" }}
            - v0.2-bower-cache-{{ .Branch }}
            - v0.2-bower-cache-master-{{ checksum "bower.json" }}
            - v0.2-bower-cache-master

      - restore_cache:
          keys:
            - v0.2-output-cache-{{ .Branch }}-{{ checksum "dist/main.js" }}
            - v0.2-output-cache-{{ .Branch }}
            - v0.2-output-cache-master-{{ checksum "dist/main.js" }}
            - v0.2-output-cache-master

      - run:
          name: Verify the project builds and tests run successfully
          command: make test
          environment:
            # The machines might have more cores than `purs` can actually use.
            # Set the number of threads to two (the cores we have available).
            RTS_ARGS: +RTS -N2 -RTS

      - save_cache:
          key: v0.3-npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/lynx/node_modules

      - save_cache:
          key: v0.2-bower-cache-{{ .Branch }}-{{ checksum "bower.json" }}
          paths:
            - ~/lynx/bower_components

      - save_cache:
          key: v0.2-output-cache-{{ .Branch }}-{{ checksum "dist/main.js" }}
          paths:
            - ~/lynx/output

workflows:
  version: 2
  build:
    jobs:
      - test
