apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "standard-web.fullname" . }}
  labels:
    app: {{ template "standard-web.name" . }}
    chart: {{ template "standard-web.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ template "standard-web.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "standard-web.name" . }}
        release: {{ .Release.Name }}
        repository: {{ .Release.Name }}-local
        imageTag: latest
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "lynx-local:latest"
          command: ["make", "serve"]
          volumeMounts:
            - name: src
              mountPath: /usr/src/app
          imagePullPolicy: IfNotPresent
          env: []
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: althttp
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /index.html
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /index.html
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 10
          resources: {}
        {{- if .Values.watch }}
        - name: {{ .Chart.Name }}-watch
          image: "lynx-local:latest"
          command: ["make", "watch"]
          volumeMounts:
            - name: src
              mountPath: /usr/src/app
          imagePullPolicy: IfNotPresent
          env: []
        {{- end }}
      volumes:
        - name: src
          hostPath:
            type: Directory
            path: {{ .Values.persistence.path }}
      nodeSelector: {}
      affinity: {}
      tolerations: []
